import { Red_Rose, Sora } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/UI/nav-bar";
import Footer from "@/components/UI/footer";

const sora = Sora({
  variable : "--font-sora",
  weight : ["400", "700"],
  subsets : ['latin'],
});

const redRose = Red_Rose({
  variable : "--font-rose",
  weight : ["400", "700"],
  subsets : ['latin']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${redRose.variable} antialiased`}
      >
        <NavBar/>
          {children}
        <Footer />
      </body>
    </html>
  );
}
